"use client"
import React, { useState } from 'react';
import Footer from '@/Components/Footer/Footer'
import Navbar from '@/Components/navigation/Navbar'
import { CartContext, CartWrapper } from '@/context/index'
import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  const [cart, setCart] = useState([]);

  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar/>
        <CartContext.Provider value={{cart, setCart}}>
          {children}
        </CartContext.Provider>
        <Footer/>
      </body>
    </html>
  )
}
