// RootLayout.js

import React from 'react';
import Footer from '@/Components/Footer/Footer'
import Navbar from '@/Components/navigation/Navbar'
import { CartProvider } from '@/context/index' // Import CartProvider
import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar/>
        <CartProvider> {/* Use CartProvider to wrap your components */}
          {children}
        </CartProvider>
        <Footer/>
      </body>
    </html>
  )
}
